#!/bin/sh
# check if we are on real system
if [ -z "$${IPKG_INSTROOT}" ]; then
    if [ -f "/etc/mosdns/config.yaml" ]; then
        cp -f "/etc/mosdns/config.yaml" "/tmp/mosdns_config.bak" >/dev/null 2>&1
    fi
fi
exit 0
