#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
/etc/init.d/mosdns stop
/etc/init.d/mosdns disable
if [ -f "/etc/mosdns/config.yaml" ]; then
    cp -f "/etc/mosdns/config.yaml" "/etc/mosdns/config.bak.yaml"
fi
exit 0
